* Inform-kirjaston 6/11 kotoistus (dokumentaatio)

Inform 6 on ohjelmointijuttu tekstiseikkailupelien kehittelyä varten, tämä on sen kirjaston 6/11 kotoistuksen dokumentaatio suomenkielelle tai ainakin yrittää olla.

** TODO (info) inform
- mikä? mitä, kuka, missä? mikä maailma tämä on?

** TODO esimerkkipelit 
-> missä!? (eri repossa)
-> demo?

*** adventin aika
seikkailu tai advent on pääasiallinen esimerkki 

*** lelukauppa
lelukaupassa on erilaisempia olioita kuin seikkailussa

** ad hoc 
- osittain toimii riittävän hyvin "ad hoc"?
- kyhäelmiä (huonoja) jotka pitäisi kirjoittaa uudelleen (ks. esim. nominien taivutuksen tulostaminen)

** TODO (info) tulkit
- fizmo
- frotz

** TODO kääntäjä
- kääntäjä syö iso8859:ä (ei utf8 tms) 

** nominien taivutuksen *tulostaminen*

Nominien taivutuksen tulostaminen on nykyisellään erittäin epäkäytännöllistä. 

Jotta olion nimi saadaan ohjelmallisesti taivutettua ja tulostettua,
täytyy antaa 5 taivutusta käsin -- ohjelma tulostaa loput 6 taivutusmuotoa (fifty-sixty?).

#+BEGIN_SRC
   "kapsäk/ki", gen "in", par "kiä", ess "kinä", ill "kiin"
#+END_SRC

Merkkijonot jaetaan kauttaviivalla "/" ennen astevaihtelua, tai jos
astevaihtelua ei esiinny, menee "/" taivutettavan sanan loppuun.

Merkkijonoihin =gen=, =par=, =ess= ja =ill= nysvätään se osa sanavartaloa joka tulee
astevaihtelun jälkeen, plus pääte.

*** omistusmuotojen tulostaminen

Omistusmuotoja tulostettaessa lisätään kauttaviiva ja
omistusliite nimen perään, mutta esimerkiksi "kapsäkkisi" (lelukauppa) tarvitsee lisäapua (lelukauppa):

#+BEGIN_SRC
Object satchel "kapsäk/ki/si"
[...]
     gen "in", par "kiä", ess "kinä", ill "kiin",
 	     short_name
	     [; if (Sija == csGen) {print "kapsäkkisi"; rtrue;};
 		if (Sija == csIll) {print "kapsäkkiisi"; rtrue;};
		if (Sija == csTra) {print "kapsäkiksesi"; rtrue;};
		rfalse;],
#+END_SRC

*** oletus partitiivi

Antamalla oliolle ominaisuuden =oletus_par= nimi ei tulostu
oletusarvoisesti perusmuodossa vaan
partitiivissa - esim. "Täällä on maukasta ruokaa".

Taivutusta voi testata verbillä *sijat*.

#+BEGIN_SRC
>sijat auto

  Oletus (name): pieni punainen auto
  Nominatiivi 1: pieni punainen auto
  Partitiivi  3: pientä punaista autoa
  Genetiivi   2: pienen punaisen auton
  Essiivi    10: pienenä punaisena autona
  Inessiivi   4: pienessä punaisessa autossa
  Illatiivi   6: pieneen punaiseen autoon
  Elatiivi    5: pienestä punaisesta autosta
  Adessiivi   7: pienellä punaisella autolla
  Ablatiivi   8: pieneltä punaiselta autolta
  Translat.  11: pieneksi punaiseksi autoksi
  Allatiivi   9: pienelle punaiselle autolle
#+END_SRC

*** monikon tulostaminen

Monikko tulostetaan antamalla oliolle ominaisuus 'pluralname'. Joskus (!) monikko tarvitsee myös
tulostusohjeen =ine=, jotta taivutus tulostuu oikein:

#+BEGIN_SRC c
!! ao. tarvitsee ine:n - muuten tulostaa "likapyykkeiksi" yms

Object "likapyyk/it" with gen "kien", par "kejä", ess "keinä", ill "keihin", ine "eissä", has pluralname;
#+END_SRC c

*** TODO hakujuttu nykysuomen sanalistasta 
Kotimaisten kielten keskuksen sanalistasta voisi kehittää jonkinlaisen hakujutun.

http://kaino.kotus.fi/sanat/nykysuomi/
(GNULPL)

Jonkinlainen "esikääntäjä" (?) kenties jolla haettaisiin olioiden nimet lähdetekstistä -> sanalistasta niiden taivutus- ja astevaihtelutiedot, jotka kirjoitettaisiin joko suoraan näytölle tai lähdetekstiin.

- (esikääntäjän) tulostus *ei mielellään merkkijonoina* nykyiseen tyyliin:  
#+BEGIN_SRC
short_name "spede/", gen "n", par "ä", ess "nä", ill "en"
#+END_SRC

vaan *mielummin taulukko* (array), esimerkiksi?
- ohjelman tuottama taulukko / merkkijono täytihmisen luettava myös

esimerkiksi kapsäkki löytyy listasta, mutta spede ei löydy. 
Spede taitaa taipua samoin (5)?

kapsäkki tn 5 av A
spede tn (5?) av (?)

- voisi olla hyödyllistä jos nykyinen (puklu) osaisi päätellä annetuista merkkijonoista (=gen par ess ill=) taivutustiedot

*kapsäkki*
tn 5 risti 
av A takki kk:k

*spede*
tn 8 nalle
av - (ei astevaihtelua)


- ! listassa on myös verbien taivutus
- ! puklussa voisi olla (tulee olemaan?) valmiina malliolioita (nominit): takki (tn 5), risti (av A) jne. 
- myös verbit (myöhemmin?): liikkua (av A) jne... 
- ? täytyisi vain tietää loppuuko a/ä ja voisi toteuttaa paljon nyk. puklulla

#+BEGIN_SRC
short_name "spede/", tt 
kapsäkki tn 5 av A

#+END_SRC

- lisäksi parempi (varsinainen) tulostusjuttu joka ymmärtää sanalistan sanatietueiden elementit ja osaa niiden perusteella tehdä taivutukset. 
- myös kiinnostavaa parsimisen kannalta! (esim. astevaihtelun vahva vai heikko muoto)
- yhdenmukaistaminen (puklu) sanatietuiden kanssa 

- *parhaimmillaan* esikääntäjä olisi toteutettu informilla, ja olisi yhteensopiva nyk. materiaalin kanssa ja lähes täysin automaaginen. Sanoista joita ei löytyisi listasta (esim. erisnimet), esikääntäjä tekisi valistuneita arvauksia. 

- *nollaratkaisu:* lunttaat taivutuksia ja astevaihteluita suomenkielisestä wiktionarystä ja teet taivutukset (noin puolet taivutuksista) käsin kuten nykyään.

** TODO (villikortti tms.) parsiminen on kömpelöä

Olioiden sanakirjanimissä (name) on vieläkin tällaista: "punainen" "punaise" "punais" (vaikka ei pitäisi)

Vahva vai heikko astevaihtelu?
Esimerkiksi jos pelissä on Maukka ja maukasta ruokaa, käsky
"anna maukalle maukasta"
Ei välttämättä toimi ilman parsimisohjeita tyyliin:
Maukka: vahva_a 'maukka', heikko_a 'mauka'
Ja maukas ruoka: vahva_b 'maukkaa', heikko_b 'maukas'
** TODO (info) pitkien nimien resoluutio sanakirjasanat (9 merkkiä)?
ei ole aiheuttanut pulmia tähän asti joten miksi?
** TODO glulx-tuki
puuttuu!
** pläp

Kirjaston suomenkielistämisjuttu on (c) ihvi-työryhmä 2004-2020. Sen käyttöehtojen on tarkoitus olla samanlaiset kuin Inform-kirjaston https://gitlab.com/DavidGriffith/inform6lib/-/blob/master/COPYING

